export const SKILLS = [
  {
    category: "Backend",
    subtitle: "Building scalable APIs & distributed systems",
    accent: "blue",
    technologies: [
      "Node.js",
      "Express.js",
      "Python",
      "FastAPI",
      "Java",
      "MongoDB",
      "PostgreSQL",
      "SQL",
      "Redis",
      "JWT Authentication",
      "Socket.io",
      "Kafka",
    ],
  },
  {
    category: "Frontend",
    subtitle: "Creating modern responsive user interfaces",
    accent: "purple",
    technologies: [
      "React",
      "TypeScript",
      "JAVASCRIPT",
      "Next.js",
      "Framer Motion",
      "Tailwind CSS",
      "HTML",
      "CSS",
    ],
  },
  {
    category: "Tools",
    subtitle: "Development workflow & deployment",
    accent: "emerald",
    technologies: ["Git", "GitHub", "Docker", "Linux", "Postman", "VS Code" , "LangChain", "LangGraph",],
  },
  {
    category: "Concepts",
    subtitle: "Core computer science foundations",
    accent: "amber",
    technologies: [
      "DSA",
      "REST APIs",
      "JWT",
      "Distributed Systems",
      "System Design",
      "OOP    ",
      "Generative AI",
      "LLMs",
      "RAG",
      "Vector Databases",
      "Embeddings",
    ],
  },
];
